### ISSUE TITLE
[Welcome] Long whisper messages causes error when getting settings

### ISSUE THREAD

**Issue by brandons209** [tmercswims/tmerc-cogs#100]
### I am submitting a...
```
 [ ] Bug report
 [X] Feature request or improvement for an existing cog
```

### Name of the cog in question:
Welcome

### Description of my issue/request:
Running [p]welcomeset with a whisper messages > 1024 characters, an exception is thrown. Whisper message should be clipped if its too long, as an example here:

```python
format(j['enabled'], j['delete'], jw['state'], jw['message'] if len(jw['message']) <= 50 else jw['message'][:50] + "...", len(j['messages']), j['bot'],
                 prefix=ctx.prefix))
```

**Comment by tmercswims** [comment]
Also closed by #101.
