### ISSUE TITLE
[NestedCommands] Conflicts with Crier from CogsByAdrian

### ISSUE THREAD

**Issue by LGACode** [tmercswims/tmerc-cogs#105]
**Cog in question**
Which cog is having an issue? NestedCommands

**Describe the bug**
A clear and concise description of what the problem is.

NestedCommands conflicts with Crier because both use `say` as one of their commands. Please consider changing your `say` to `repeat` instead as I feel that it fits your action more than `say` compared to Crier.

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by tmercswims** [comment]
Definitely fair. I intend for my instance of `say` to be mostly a utility for testing, anyway. I will change the name of it to `[p]echo`.
