### ISSUE TITLE
[MassDM] needs a warning as sending out too many DM's will get the bot flagged by discord anti-spam system

### ISSUE THREAD

**Issue by Skyridr** [tmercswims/tmerc-cogs#111]
As of last week, I attempted to use the MassDM command to let people know regarding a few things. However, at some point the bot was blocked from sending DM's as it was triggered by Discord's anti-spam system which prevented the bot to send further DM's.

> Your bot has been flagged by our anti-spam system for abusive behavior. While your bot is quarantined, it is unable to join any more guilds, or send any direct messages to users it has not messaged before. If you believe this to be in error, click here and select "Appeal an Action Trust and Safety took on my bot" as the Report Type to submit an appeal.

I believe this particular discord feature was added as of late last year.

**Comment by tmercswims** [comment]
I agree, users should be informed of this, especially since it seems that Discord's definition of "too many messages too quickly" has continued to shrink recently. I will add a warning to the post-install message.
