### ISSUE TITLE
randimals support for bunnies and ducks

### ISSUE THREAD

**Issue by Plichso** [tmercswims/tmerc-cogs#112]
#### Cog in question

randimals

#### Is your feature request related to a problem? Please describe.

I was disappointed to see, there is no command for ducks and bunnies

#### Describe the solution you'd like
I found an API for duck images and bunny images
Ducks: https://random-d.uk/api/random
Bunnies: https://api.bunnies.io/v2/loop/random/?media=gif

**Comment by tmercswims** [comment]
Nice! I'm always up for adding more animals to randimals :)

Note for myself: While trying to find API docs for bunnies.io, I came across [this NPM package](https://github.com/treboryx/animalsAPI), which shows off some other animal image APIs that I will also add.
