### ISSUE TITLE
[streamrole] Fights with the YAGPDB.xyz bot

### ISSUE THREAD

**Issue by VenoPhage** [tmercswims/tmerc-cogs#117]
#### Cog in question

streamrole

#### Describe the bug

Currently I have a role that yag is set to ignore the problem is its not so much as a ignore as a don't let this user have this role this seems to be the same case with this cog thus causing a feedback loop where the cog gives me the role and yag removes it.

#### Expected behavior

Something that detects this spam and prevents it this is a issue with both yag and this cog and both would have to change for the issue to be resolved completely

**Comment by VenoPhage** [comment]
The reason I have two bots that do the same thing is to have two separate messages so a alternative fix would be to allow to set a specific message for a specific member

**Comment by tmercswims** [comment]
I'm sorry, and I promise I'm not trying to be rude, but I think the fits pretty squarely in the hole of "that sounds like a you problem." I want to keep StreamRole a fairly simple cog, and not get into super-complex conditions which control whether or not the role should be added or try to accommodate every setup that people have.
