### ISSUE TITLE
bug emoji and special characters and mention 

### ISSUE THREAD

**Issue by Andrea-98** [tmercswims/tmerc-cogs#119]
when you insert custom or default discord emojis or special characters such as commas or periods these are not displayed or even do not show the message in welcome, leave or ban. It is not possible to mention the server and users

**Comment by Andrea-98** [comment]
it is not possible to mention the server and users

**Comment by tmercswims** [comment]
Regarding the special character/emoji issue:
Can you provide some examples of messages that don't work, and also some screenshots of how they do look when the bot sends them? I just did some testing on my own, and messages that have punctuation and custom emojis all appear to be working fine for me.

Regarding server/user mentions:
First of all, servers cannot be mentioned. Users can be mentioned, by putting `{member.mention}` in the message format. I just tested this out for myself as well, and it also works. Could you give me more detail about what you're doing? The message exactly, for instance? You can get a list with `[p]welcome <type> msg list` where `<type>` is `join`, `leave`, etc.

**Comment by tmercswims** [comment]
If you can reproduce this and are able to provide more information please feel free to comment again. For now, I will close this.
