### ISSUE TITLE
[Suggestion] StreamRole: Game Specific Setting

### ISSUE THREAD

**Issue by Menteroth** [tmercswims/tmerc-cogs#122]
#### Cog in question
StreamRole

#### Describe alternatives you've considered
To only add the streaming role if a specific game has been set. Or possibly more than just one game.
Great for game specific servers where you only want that game to be hoisted for livestreams.

**Comment by tmercswims** [comment]
Thank you for the suggestion! Assuming I'm reading this right, I think the idea is covered by the first point in #121. As such, I will close this as a duplicate, and I'll consider it a vote in favor of #121.

**Comment by Menteroth** [comment]
Oh. I read that totally wrong. It is yes.
