### ISSUE TITLE
[Randimals] "koala" and "panda" commands broken

### ISSUE THREAD

**Issue by ajwsert** [tmercswims/tmerc-cogs#124]
The "koala" and "panda" commands are broken due a change on some-random-api, it changed from https://some-random-api.ml/ to  https://some-random-api.com/ (see https://github.com/telkenes/some-random-api/issues/12).

**Comment by tmercswims** [comment]
Thank you for noticing! I've just pushed a fix for this, `[p]cog update` should get you the new version.
