### ISSUE TITLE
[Randimals] Removal of working endpoints, maybe reformat

### ISSUE THREAD

**Issue by Technetium1** [tmercswims/tmerc-cogs#125]
#### Cog in question
**Randimals**

#### Is your feature request related to a problem? Please describe.
Suddenly there are 2 commits removing kangaroo and raccoon, this is sad.

#### Describe the solution you'd like
Maybe revert the commits? Support all the possible image endpoints? They seem to all be formatted the same way in https://some-random-api.com/docs/animal

#### Describe alternatives you've considered
- If they were removed because they weren't working, it makes sense to say what the error fetching the image is each time, _alongside_ unable to get `{animal}` picture.
- Unify the command with a list, but I don't know that the `@commands.hybrid_command()` decorator allows for this gracefully.
	- I used an LLM and reformatted the output, maybe it's possible? https://bin.garudalinux.org/?bd9cb579fe41a263#APL3tejGuzYofBf1AG4yD7gCvUndpN51CdzFA7THKBVU

#### Additional context
- kangaroo removal: https://github.com/tmercswims/tmerc-cogs/commit/6e165d94300186b8dc354bba74a57ffd16ded101
- raccoon removal: https://github.com/tmercswims/tmerc-cogs/commit/3343d644229b465f767c2855e92d18494e2adc89

**Comment by tmercswims** [comment]
They were removed because the API only has one image for each, so it's not random. I'll check them periodically, and if they add more images then I'll readd the commands.

As for the list suggestion, unfortunately it isn't possible because each command needs to be its own method in the class. And I don't know what that LLM output is doing, it's full of made-up junk (as is typical with LLM-generated anything).

**Comment by Technetium1** [comment]
> They were removed because the API only has one image for each, so it's not random

Oh I see now, it's only the facts that are randomized

> I'll check them periodically, and if they add more images then I'll readd the commands

Fantastic, hopefully it's updated, though it seems the creator passed away, so who knows the future of new features: https://some-random-api.com/tribute

> As for the list suggestion, unfortunately it isn't possible because each command needs to be its own method in the class. And I don't know what that LLM output is doing, it's full of made-up junk (as is typical with LLM-generated anything).

Wishful thinking. I'm disappointed, though not unexpectedly. Thanks for having a look at it anyway! Feel free to reopen this if the endpoints get some random animals or the command structure changes in a relevant way.
