### ISSUE TITLE
[Survey] Error in command 'closesurvey'

### ISSUE THREAD

**Issue by terawo** [tmercswims/tmerc-cogs#25]
### I am submitting a...
 - [x] Bug report
 - [ ] Feature request or improvement for an existing cog
 - [ ] Request for a new cog

### Name of the cog in question:
Survey

### Description of your issue/request:
Receive the following error message when trying to close a survey:
`Error in command 'closesurvey' - KeyError: 'closed'`

### If it's a bug, provide steps to reproduce:
 

1. Create a survey

2. Attempt to close survey

### If it's a bug, provide a stack trace:
```
[27/10/2016 06:22] ERROR red on_command_error 88: Exception in command 'closesurvey'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/kinshikuma/Red-DiscordBot/cogs/survey.py", line 524, in _closesurvey
    if survey_id in self.surveys["closed"]:
KeyError: 'closed'
```

**Comment by tmercswims** [comment]
Can you copy paste here the content of the file `data/survey/surveys.json`, please?

**Comment by terawo** [comment]
{
    "218081755058536448" : {
        "1" : {
            "answers" : {
                "player1" : [],
                "player2" : [],
                "player3" : [],
                "player4" : []
            },
            "asked" : [
                "205074789465849857"
            ],
            "channel" : "218371333900337152",
            "deadline" : "100",
            "messages" : {
                "results" : "241079208191852545",
                "waiting" : "241079208992833536"
            },
            "options" : {
                "player1" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player2" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player3" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player4" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                }
            },
            "prefix" : ".",
            "question" : "Vote for who on your team you want to betray"
        },
        "2" : {
            "answers" : {
                "player1" : [],
                "player2" : [],
                "player3" : [],
                "player4" : []
            },
            "asked" : [
                "205074789465849857"
            ],
            "channel" : "218371333900337152",
            "deadline" : "7pm",
            "messages" : {
                "results" : "241079382276309002",
                "waiting" : "241079382620241921"
            },
            "options" : {
                "player1" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player2" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player3" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player4" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                }
            },
            "prefix" : ".",
            "question" : "Vote for who on your team you want to betray"
        },
        "3" : {
            "answers" : {
                "player1" : [],
                "player2" : [],
                "player3" : [],
                "player4" : []
            },
            "asked" : [
                "205074789465849857"
            ],
            "channel" : "218371333900337152",
            "deadline" : "7pm",
            "messages" : {
                "results" : "241080344827265034",
                "waiting" : "241080345447890944"
            },
            "options" : {
                "player1" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player2" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player3" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player4" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                }
            },
            "prefix" : ".",
            "question" : "Vote for who on your team you want to betray"
        }
    },
    "next_id" : 4
}

**Comment by terawo** [comment]
`{
    "218081755058536448" : {
        "1" : {
            "answers" : {
                "player1" : [],
                "player2" : [],
                "player3" : [],
                "player4" : []
            },
            "asked" : [
                "205074789465849857"
            ],
            "channel" : "218371333900337152",
            "deadline" : "100",
            "messages" : {
                "results" : "241079208191852545",
                "waiting" : "241079208992833536"
            },
            "options" : {
                "player1" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player2" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player3" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player4" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                }
            },
            "prefix" : ".",
            "question" : "Vote for who on your team you want to betray"
        },
        "2" : {
            "answers" : {
                "player1" : [],
                "player2" : [],
                "player3" : [],
                "player4" : []
            },
            "asked" : [
                "205074789465849857"
            ],
            "channel" : "218371333900337152",
            "deadline" : "7pm",
            "messages" : {
                "results" : "241079382276309002",
                "waiting" : "241079382620241921"
            },
            "options" : {
                "player1" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player2" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player3" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player4" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                }
            },
            "prefix" : ".",
            "question" : "Vote for who on your team you want to betray"
        },
        "3" : {
            "answers" : {
                "player1" : [],
                "player2" : [],
                "player3" : [],
                "player4" : []
            },
            "asked" : [
                "205074789465849857"
            ],
            "channel" : "218371333900337152",
            "deadline" : "7pm",
            "messages" : {
                "results" : "241080344827265034",
                "waiting" : "241080345447890944"
            },
            "options" : {
                "player1" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player2" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player3" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player4" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                }
            },
            "prefix" : ".",
            "question" : "Vote for who on your team you want to betray"
        }
    },
    "next_id" : 4
}`

**Comment by terawo** [comment]
{
    "218081755058536448" : {
        "1" : {
            "answers" : {
                "player1" : [],
                "player2" : [],
                "player3" : [],
                "player4" : []
            },
            "asked" : [
                "205074789465849857"
            ],
            "channel" : "218371333900337152",
            "deadline" : "100",
            "messages" : {
                "results" : "241079208191852545",
                "waiting" : "241079208992833536"
            },
            "options" : {
                "player1" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player2" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player3" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player4" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                }
            },
            "prefix" : ".",
            "question" : "Vote for who on your team you want to betray"
        },
        "2" : {
            "answers" : {
                "player1" : [],
                "player2" : [],
                "player3" : [],
                "player4" : []
            },
            "asked" : [
                "205074789465849857"
            ],
            "channel" : "218371333900337152",
            "deadline" : "7pm",
            "messages" : {
                "results" : "241079382276309002",
                "waiting" : "241079382620241921"
            },
            "options" : {
                "player1" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player2" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player3" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player4" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                }
            },
            "prefix" : ".",
            "question" : "Vote for who on your team you want to betray"
        },
        "3" : {
            "answers" : {
                "player1" : [],
                "player2" : [],
                "player3" : [],
                "player4" : []
            },
            "asked" : [
                "205074789465849857"
            ],
            "channel" : "218371333900337152",
            "deadline" : "7pm",
            "messages" : {
                "results" : "241080344827265034",
                "waiting" : "241080345447890944"
            },
            "options" : {
                "player1" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player2" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player3" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                },
                "player4" : {
                    "limit" : null,
                    "link" : null,
                    "reprompt" : null
                }
            },
            "prefix" : ".",
            "question" : "Vote for who on your team you want to betray"
        }
    },
    "next_id" : 4
}

**Comment by tmercswims** [comment]
That is... very weird, to say the least. `closed` is added as part of the default configuration... And I'm guessing you haven't edited this file manually, correct?

**Comment by terawo** [comment]
Which file? The survey.json file?

**Comment by terawo** [comment]
I’m going to delete the cog and reinstall it from scratch. I probably changed something in the .json. If that’s the problem, then this is the way to fix it.

**Comment by terawo** [comment]
Alright, that must've fixed it.

It appears that I must've removed the `"closed" : [],` in the default version of the .json when I was testing it.

I'll do a few checks first to make sure I've actually fixed it.

**Comment by terawo** [comment]
Yes it works.

Thanks for your help.
