### ISSUE TITLE
[Survey] If an absolute deadline, with date, is more than one day in the past, no error occurs.

### ISSUE THREAD

**Issue by tmercswims** [tmercswims/tmerc-cogs#31]
Instead, the deadline is pushed forward one day (as if it was given as just a time).

**Comment by skeith** [comment]
Where can I read about this python limitation?

**Comment by tmercswims** [comment]
The Python limitation is mentioned in the documentation here: https://docs.python.org/3/library/asyncio-eventloop.html#delayed-calls and discussed a little more in-depth here: https://bugs.python.org/issue20493. Though that limitation and this issue are unrelated.

**Comment by skeith** [comment]
What if we calculate the delay of the deadline, then split them into several records, with each record delay last for one day

**Comment by tmercswims** [comment]
Closing, as Survey will be reincarnated differently in v3.
