### ISSUE TITLE
MDM can't use roles with more than one word

### ISSUE THREAD

**Issue by Lionirdeadman** [tmercswims/tmerc-cogs#49]
### I am submitting a...
```
 [ ] Bug report
 [ X ] Feature request or improvement for an existing cog
```

### Name of the cog in question:
massdm

### Description of my issue/request: 
The cog can't handle roles which use more than one word

**Comment by skeith** [comment]
Did you try enclosing the said role name with double quotes?

**Comment by Lionirdeadman** [comment]
Oh.. I'm stupid, sorry.
