### ISSUE TITLE
[Survey] Add support for anonymous voting / numbers instead of usernames

### ISSUE THREAD

**Issue by ghost** [tmercswims/tmerc-cogs#59]
### I am submitting a...
```
 [ ] Bug report
 [ x ] Feature request or improvement for an existing cog
```

### Name of the cog in question:
survey

### Description of my issue/request:
An option so it just shows the number of people who voted for it which choice instead of their usernames.
This would be better for people with large servers or if you want to make the vote anonymous.

**Comment by tmercswims** [comment]
Closing, as Survey will be reincarnated differently in v3.
