### ISSUE TITLE
[Survey] Auto-add new members who have the role used in survey

### ISSUE THREAD

**Issue by ghost** [tmercswims/tmerc-cogs#60]
### I am submitting a...
```
 [ ] Bug report
 [ x ] Feature request or improvement for an existing cog
```

### Name of the cog in question:
survey

### Description of my issue/request:
Ability for the cog to add members who get the role after the survey has started.

**Comment by tmercswims** [comment]
Closing, as Survey will be reincarnated differently in v3.
