### ISSUE TITLE
[Bug] Playsound unable to stop audio cog and\or check if is playing

### ISSUE THREAD

**Issue by xzyxzy** [tmercswims/tmerc-cogs#63]
If you try to play mp3\m4a while youtube is playing it will crash but with this msg.
http://i.imgur.com/hV17QUt.png

If you try to play wav file while youtube is playing it will start  switching back and forth each _buffer amount of time in ffmpeg?_ between two streams, can record audio of that if needed.
Then it will give up on producing sound and print this error message repeatedly.
http://pastebin.com/ggCmVtB1

It does works as intended with all 3 formats mentioned when youtube is not playing.

**Comment by tmercswims** [comment]
I'm closing this, as PlaySound is now deprecated in favor of sfx.
