### ISSUE TITLE
[streamrole] Give role, if someone is playing game

### ISSUE THREAD

**Issue by jack1142** [tmercswims/tmerc-cogs#74]
### I am submitting a...
```
 [ ] Bug report
 [ x ] Feature request or improvement for an existing cog
```

### Name of the cog in question:

streamrole

### Description of my issue/request:

I want to give roles, if someone is playing game right now and take it back, if he stop playing it.

**Comment by Technetium1** [comment]
I would like to second this request

**Comment by tmercswims** [comment]
Superseded by #121.
