### ISSUE TITLE
Command Doesn't Work

### ISSUE THREAD

**Issue by EchoStaff** [tmercswims/tmerc-cogs#78]
### I am submitting a...
```
 [ 1 ] Bug report
```

### Name of the cog in question:
Customjoinleave

### Description of my issue/request:
The cog wont load onto the bots files or work at all

### If it's a bug, steps to reproduce:
 
 1. Maybe update the commands files

### If it's a bug, a stack trace:
```
Paste it here.
```
Its to long i cant copy it

**Comment by skeith** [comment]
Stack trace needs to be posted, no matter how long.

**Comment by tmercswims** [comment]
Yes, the stack trace is pretty much required, and so is some actual information. Just saying "it doesn't work" gives me absolutely no information with which to try and solve your problem.

**Comment by tmercswims** [comment]
Closing this as no new information has been given.
