### ISSUE TITLE
Not removing role

### ISSUE THREAD

**Issue by TheWyn** [tmercswims/tmerc-cogs#90]
### I am submitting a...
```
 [X] Bug report
 [ ] Feature request or improvement for an existing cog
```

### Name of the cog in question:

Streamrole V3 version

### Description of my issue/request:

When a user stops streaming, bot almost never removes the role.  And gives the exception link below.  It is not a permission error as the bot has full administrator power and is higher on the role hierarchy, if it was a permission error I would have received the forbidden trace.

According to d.py rewrite docs only other exception that can be thrown is a HTTPException.

### If it's a bug, steps to reproduce:
 
 1. Watch user get stream role as usual, then watch red.log show the exception when user stops streaming

### If it's a bug, a stack trace:

https://github.com/tmercswims/tmerc-cogs/blob/v3/streamrole/streamrole.py#L221

**Comment by tmercswims** [comment]
@Wyn10 I realize that this issue is very, _very_ old, and my sincerest apologies for not responding sooner. Is this still an issue for you?
